version: '2.1'

services:
  webgoat:
    image: webgoat/webgoat-8.0
    environment:
      - WEBWOLF_HOST=webwolf
      - WEBWOLF_PORT=9090
      - spring.datasource.url=jdbc:hsqldb:hsql://webgoat_db:9001/webgoat
    ports:
      - "8080:8080"
    depends_on:
      - db
  webwolf:
    image: webgoat/webwolf
    environment:
          - spring.datasource.url=jdbc:hsqldb:hsql://webgoat_db:9001/webgoat
    ports:
      - "9090:9090"
    depends_on:
      - db
  db:
    image: blacklabelops/hsqldb
    container_name: webgoat_db
    environment:
      - HSQLDB_TRACE=false
      - HSQLDB_SILENT=true
      - HSQLDB_DATABASE_NAME=webgoat
      - HSQLDB_DATABASE_ALIAS=webgoat
